version: '2'

volumes:
    local_datamongo: {}
    local_dataelasticsearch: {}

services:
    php:
        build: docker/php7-fpm
        volumes:
            - ./sites/irufy:/var/www/irufy
            - ./docker/logs/irufy:/var/www/irufy/app/logs

    nginx:
        build: docker/nginx
        ports:
            - 9889:80
        volumes_from:
            - php
        volumes:
            - ./docker/logs/nginx/:/var/log/nginx

    db:
        image: mysql:5
        volumes:
              - "./docker/data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: 12345678
            MYSQL_DATABASE: irufy
            MYSQL_USER: irufy
            MYSQL_PASSWORD: 12345678

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 9898:80
        links:
            - db:db

